import os
import re

screens = [
    ("S-01", "Login & Workspace Selection", "/login", "app/login"),
    ("S-02", "Owner Portfolio Dashboard", "/dashboard/owner", "app/dashboard/owner/page.tsx"),
    ("S-03", "Today / PM Task Queue Dashboard", "/dashboard/pm", "app/dashboard/pm/page.tsx"),
    ("S-04", "Leasing Dashboard", "/dashboard/leasing", "app/dashboard/leasing/page.tsx"),
    ("S-05", "Finance Dashboard", "/dashboard/finance", "app/dashboard/finance/page.tsx"),
    ("S-06", "Approvals Inbox", "/approvals", "app/approvals/page.tsx"),
    ("S-10", "Rent Roll Register", "/operate/rent-roll/register", "app/operate/rent-roll/register/page.tsx"),
    ("S-11", "Property Form", "/masters/property", "MasterDataModal.tsx (Property Tab)"),
    ("S-12", "Building Form", "/masters/building", "MasterDataModal.tsx (Building Tab)"),
    ("S-13", "Space Form (incl. Seat Inventory)", "/masters/space", "MasterDataModal.tsx (Space Tab)"),
    ("S-14", "Occupant Form", "/masters/occupant", "MasterDataModal.tsx (Occupant Tab)"),
    ("S-15", "Pricing Plan (Flex & Seats add-on)", "/masters/pricing", "MasterDataModal.tsx / pricing plans"),
    ("S-18", "Deal Register & Deal Form", "/deals", "DealsRegisterView.tsx"),
    ("S-21", "Create / Edit Contract (7-step Wizard)", "/contracts/wizard", "ContractWizardModal.tsx"),
    ("S-22", "Contract Detail", "/contracts/[id]", "ContractDetailDrawer.tsx"),
    ("S-23", "Documents Repository", "/documents", "DocumentViewerModal.tsx"),
    ("S-24", "Expiry Pipeline & Renewals", "/expiry", "ExpiryPipelineView.tsx"),
    ("S-25", "Escalation Calendar & Apply", "/escalations", "EscalationCalendarView.tsx"),
    ("S-26", "Occupancy & Stacking Plan", "/occupancy", "Stacking Plan / Space viewer"),
    ("S-30", "Import Centre (6-step Wizard)", "/import", "DataImportView.tsx"),
    ("S-31", "Meter Readings", "/meters/readings", "Meter readings entry"),
    ("S-32", "Seat Counts (Flex)", "/flex/seat-counts", "Seat counts entry"),
    ("S-40", "Billing Centre & Billing Run", "/billing/run", "Invoice generation batch / modal"),
    ("S-41", "Invoice Detail", "/invoices/[id]", "InvoiceDetailModal.tsx"),
    ("S-42", "Credit / Debit Note", "/invoices/[id]/credit-note", "Credit note route / modal"),
    ("S-43", "Payment Centre & Record Payment", "/payments", "PaymentsCollectionsView.tsx"),
    ("S-44", "Allocation Screen", "/payments/[id]/allocate", "PaymentsCollectionsView.tsx (Allocation tab)"),
    ("S-45", "Ageing & Collections", "/collections/ageing", "PaymentsCollectionsView.tsx (Ageing tab)"),
    ("S-46", "Disputes", "/collections/disputes", "PaymentsCollectionsView.tsx (Disputes tab)"),
    ("S-47", "Deposits", "/collections/deposits", "PaymentsCollectionsView.tsx (Deposits tab)"),
    ("S-50", "Exception Centre", "/exceptions", "Exception Centre"),
    ("S-51", "12-Month Forecast", "/analytics/forecast", "12-Month Forecast"),
    ("S-52", "Property P&L", "/analytics/pnl", "Property P&L"),
    ("S-53", "Snapshots (Month-end Lock)", "/analytics/snapshots", "Month-end Lock Snapshots"),
    ("S-54", "Monthly MIS & Investor Pack", "/reporting/mis", "Monthly MIS / Investor Pack export"),
    ("S-55", "Owner Statements (Multi-Client)", "/multi-client/statements", "OwnerStatementModal.tsx / MultiClientFlexView.tsx"),
    ("S-56", "Client Accounts & Mandates", "/multi-client/mandates", "MultiClientFlexView.tsx"),
    ("S-57", "Head Leases & Centre P&L", "/flex/centre-pnl", "MultiClientFlexView.tsx (Centre P&L)"),
    ("S-60", "Organisation, Branding & Subscription", "/settings/org", "Admin settings"),
    ("S-61", "Billing Entities", "/settings/billing-entities", "Settings billing entities"),
    ("S-62", "Charge Types & Tax Profiles", "/settings/taxes", "Charge types & tax profiles"),
    ("S-63", "Numbering & Financial Controls", "/settings/numbering", "Numbering sequences & financial controls"),
    ("S-64", "Alert Rules", "/settings/alerts", "Alert configuration"),
    ("S-65", "Meters & Tariffs", "/settings/meters", "Meters & tariffs config"),
    ("S-66", "Users, Roles & Approval Matrix", "/settings/users", "Users & RBAC matrix"),
    ("S-67", "Audit Log", "/settings/audit", "Audit log viewer"),
    ("T-01", "Tenant Home", "/portal/home", "Tenant Home dashboard"),
    ("T-02", "Invoices & Pay", "/portal/invoices", "Tenant Invoices & Pay"),
    ("T-03", "Payment & Receipt", "/portal/pay", "Tenant Payment & Razorpay"),
    ("T-04", "Payments, Receipts & Statement", "/portal/history", "Tenant Payment History & Receipts"),
    ("T-05", "Raise Dispute", "/portal/disputes", "Tenant Raise Dispute"),
    ("T-06", "My Contract", "/portal/contract", "Tenant Contract View"),
    ("T-07", "Documents", "/portal/documents", "Tenant Documents"),
    ("T-08", "Profile & Contacts", "/portal/profile", "Tenant Profile & Contacts")
]

print(f"Total Screens in Spec Catalogue: {len(screens)}")
